theme: jekyll-theme-cayman
  
title: Green Thumb
description: CPSC 481 Human Computer Interaction Term Project in User Centered Design

compress_images:
  images_path: "assets/**/*.{gif,png,jpg,jpeg,svg}"